- lib/config/navigator_config.dart
- lib/features/navigator/page_routes/tabbar_page_route.dart
After merge I noticed some errors, unused imports, conflicts so i created new PR
> fix: change tabsconfig, conflicts and errors

- lib/config/map_view_config.dart
- lib/config/transitions.dart
- lib/features/map_view/utils/map_marker_utils.dart
- lib/features/navigator/app_router.dart
TODO: Test on multiple devices
> Fix/ normalize markers size

- lib/features/science_clubs_view/repositories/science_clubs/science_clubs_repository.dart
yet one more PR today, don't rush to review but also it's not long. Hopefully I'm not harassing you with PRs (that much).
nothing fancy, just sorting behavior like described in #96
> Feat/ new sci clubs sorting rules

- lib/features/about_us_view/utils/html_util_extensions.dart
- lib/features/about_us_view/widgets/desription_section.dart
- lib/features/department_detail_view/department_detail_view.dart
- lib/features/department_detail_view/widgets/department_sliver_header_section.dart
- lib/features/department_detail_view/widgets/fields_of_study_section.dart
- lib/features/science_club_detail_view/science_club_detail_view.dart
- lib/features/science_club_detail_view/widgets/about_us_section.dart
- lib/features/science_clubs_view/widgets/science_clubs_list.dart
- lib/widgets/big_preview_card.dart
- lib/widgets/detail_views/sliver_header_section.dart
- lib/widgets/detail_views/sliver_logo.dart
- pubspec.yaml
- removed cover as it was decided in survey (#117 )
- paddings small changes (#131 )
I did little fixes and ui tweaks. 
- fixed search box in sci clubs (after I broke it in last pr)
- changed html styling a bit to unify with what I've changed in live-preview-web-form
- centered photo in big preview card
> Feat/ remove cover from department detail view

- lib/api_base/directus_assets_url.dart
- lib/features/about_us_view/about_us_view.dart
- lib/features/about_us_view/models/about_us_details.dart
- lib/features/about_us_view/models/member_data.dart
- lib/features/about_us_view/widgets/team_section.dart
- lib/features/buildings_view/building_tile.dart
- lib/features/department_detail_view/department_detail_view.dart
- lib/features/department_detail_view/widgets/science_clubs_section.dart
- lib/features/department_detail_view/widgets/sliver_header_section.dart
- lib/features/departments_view/widgets/department_card.dart
- lib/features/guide_detail_view/guide_detail_view.dart
- lib/features/guide_view/widgets/about_us_section.dart
- lib/features/guide_view/widgets/guide_tile.dart
- lib/features/home_view/widgets/buildings_section/building_card.dart
- lib/features/home_view/widgets/buildings_section/buildings_section.dart
- lib/features/home_view/widgets/departments_section/deparment_box.dart
- lib/features/home_view/widgets/news_section.dart
- lib/features/home_view/widgets/parkings_section.dart
- lib/features/home_view/widgets/science_clubs_section.dart
- lib/features/parking_chart/models/chart_point.dart
- lib/features/science_club_detail_view/science_club_detail_view.dart
- lib/features/science_clubs_view/widgets/science_club_card.dart
- lib/widgets/big_preview_card.dart
- lib/widgets/detail_views/sliver_header_section.dart
- lib/widgets/detail_views/sliver_logo.dart
- lib/widgets/optimized_directus_image.dart
- lib/widgets/wide_tile_card.dart
I did implement new widget that will download images from directus in proper size, no unneeded pixel will be transferred.
Hopefully I didn't break anything at the same time, but if you have a moment, you can check out if didn't break any image
> Feat/ optimize images on directus

- lib/config/map_view_config.dart
- lib/features/bottom_scroll_sheet/data_list.dart
- lib/features/map_view/controllers/controllers_set.dart
- pubspec.yaml
https://github.com/user-attachments/assets/ab08f5a9-c2a3-409d-b3fd-c425b40a6acb
> Feat/ animate parkings tiles

- lib/api_base/cache/remote_flush/business/flush_cache_use_cases.dart
- lib/api_base/cache/remote_flush/data/getRemoteCacheRef.graphql
- lib/api_base/cache/remote_flush/data/local_cache_ref_number_repo.dart
- lib/api_base/cache/remote_flush/data/remote_cache_ref_number_repo.dart
- lib/api_base/cache/remote_flush/presentation/flush_cache_remotely_widget.dart
- lib/api_base/cache/ttl/local_timestamp_repository.dart
- lib/api_base/cache/ttl/ttl_service.dart
- lib/api_base/cache/ttl/ttl_timestamp.dart
- lib/api_base/query_adapter.dart
- lib/api_base/schema.graphql
- lib/config/ttl_config.dart
- lib/features/offline_messages/widgets/grapgql_offline_message.dart
- lib/main.dart
we check remote number on directus and if it increased, we flush all cache
tell me what you think
> Feat/ add remote cache flushing

- lib/config/ui_config.dart
- lib/features/science_clubs_filters/widgets/chips_loading.dart
- I've removed unnecessary space
- I've added padding of 8 to chips's loading section
- Imo result's satisfactory rn
> #213 - fix tags loading view - fix

- lib/features/about_us_view/about_us_view.dart
#205 
I think is better way to write some shimmer boxes than using the same ui style us in guide view for user experience. If u think differently I can change it ofc
> feat: add shimmer effect on about us view

- lib/features/home_view/widgets/news_section.dart
- lib/features/home_view/widgets/science_clubs_section.dart
#239 
I changed container to padding widget. 
Some ss's:
> refactor: change different paddings to widget SmallHorizontalPadding

- lib/config/ui_config.dart
- lib/features/departments_view/widgets/department_card.dart
#241 
added small padding on logos
> fix: add small padding to logos

- lib/features/guide_view/guide_view.dart
- lib/l10n/app_pl.arb
#262 
Info box about developing guide
ss:
> feat: add guide info about development

- lib/features/about_us_view/about_us_view.dart
- lib/features/about_us_view/widgets/team_section.dart
> Fix/ about us freeze after scroll on open

- .fvm/flutter_sdk
- .fvm/fvm_config.json
- .github/workflows/lint_and_format.yml
- ios/Runner.xcodeproj/project.pbxproj
- lib/features/about_us_view/utils/html_util_extensions.dart
- lib/features/bottom_nav_bar/bottom_nav_bar.dart
- lib/features/bottom_scroll_sheet/drag_handle.dart
- lib/features/navigator/root_view.dart
- lib/features/navigator/utils/android_pop_bug_workaround.dart
- lib/features/parking_chart/chart_elements/chart_line.dart
- lib/features/parking_chart/parking_chart.dart
- lib/features/parkings_view/models/parking.dart
- lib/features/parkings_view/widgets/parking_wide_tile_card.dart
- lib/theme/hex_color.dart
- lib/widgets/search_box.dart
- pubspec.yaml
#300 
- If trend is unknown, no icon is displayed. Maybe we should consider using some kind of message? "Unable to determine trend", or maybe just leave it blank. In either way, imo both look better than question mark
- I've also fixed some typos  regarding parking's feature :-)
> Fix / unknown trend on parking view

- lib/config/shared_prefs.dart
- lib/features/in_app_review/business/in_app_rating_service.dart
- lib/features/in_app_review/business/in_app_rating_service_provider.dart
- lib/features/in_app_review/in_app_review.dart
- lib/features/science_clubs_filters/widgets/apply_filters_button.dart
- lib/main.dart
- lib/utils/shared_prefs_extensions.dart
- pubspec.yaml
#286 
- his day streak's at least 3
- total review prompt doesn't exceed 2
- last prompt was displayed at least 7 days ago
Testing on Android is quite difficult (please refer to [this](https://pub.dev/packages/in_app_review#testing-read-carefully)). Google Play access's needed to test if behawior works as expected so I couldn't empirically check if everything's fine on Android :-)    Since I'm not that rich yet hence don't own a Mac, iOS testing couldn't be done by me as well :-) . So if you can, please test it. You can contact me when testing on Android (I'm curious about how the internal app sharing process looks like)
> #286 feat add in app review

- lib/features/app_streak/business/get_days_use_case.dart
- lib/features/app_streak/presentation/app_streak_counter.dart
- lib/features/home_view/home_view.dart
- lib/utils/datetime_utils.dart
> Chore: hide streak counter from user

- lib/features/offline_messages/widgets/general_offline_message.dart
- lib/widgets/my_error_widget.dart
Add Align for OfflineMessage and MyErrorWidget.
> Add Align to center error text in landscape mode

- lib/config/nav_bar_config.dart
- lib/config/ui_config.dart
- lib/features/about_us_view/widgets/app_version.dart
- lib/features/app_changelog/show_changelog.dart
- lib/features/departments_view/departments_view.dart
- lib/features/guide_view/guide_view.dart
- lib/features/guide_view/guide_view_controller.dart
- lib/features/home_view/widgets/logo_app_bar.dart
- lib/features/navigation_tab_view/navigation_tab_view.dart
- lib/features/navigation_tab_view/widgets/about_the_app_tile.dart
- lib/features/navigation_tab_view/widgets/about_us_tile.dart
- lib/features/navigation_tab_view/widgets/navigation_tile.dart
- lib/features/navigation_tab_view/widgets/notification_button.dart
- lib/features/navigation_tab_view/widgets/small_tile.dart
- lib/features/navigator/app_router.dart
- lib/features/science_clubs_view/widgets/sci_clubs_scaffold.dart
- lib/l10n/app_pl.arb
- lib/theme/app_color_theme.dart
- lib/theme/colors.dart
- lib/widgets/my_splash_tile.dart
- lib/widgets/search_box_app_bar.dart
few small tasks are still to be created to complete this fully. Also the home page redesign is needed (I have a plan), but we're waiting for the action buttons first (#379)
tell me what you think
> feat: add navigation tab view

- lib/features/about_us_view/about_us_view.dart
- lib/features/department_detail_view/department_detail_view.dart
- lib/features/departments_view/departments_view.dart
- lib/features/guide_detail_view/guide_detail_view.dart
- lib/features/navigation_tab_view/navigation_tab_view.dart
- lib/features/navigator/utils/navigation_commands.dart
- lib/features/science_club_detail_view/science_club_detail_view.dart
- lib/features/science_clubs_view/widgets/sci_clubs_scaffold.dart
- lib/features/sks-menu/presentation/sks_menu_screen.dart
- lib/features/update_dialog/presentation/update_dialog_wrapper.dart
- lib/l10n/app_pl.arb
- lib/widgets/detail_views/detail_view_app_bar.dart
- lib/widgets/detail_views/pop_button.dart
- lib/widgets/search_box_app_bar.dart
> fix: correct pop view app bar buttons' titles

- lib/features/navigation_tab_view/navigation_tab_view.dart
navigation_tab_view.dart: add revirew openStoreListing behavior to review button
pretty much one liner.
Button opens store to rate app - according to guidlines
requestReview() (avoid)
openStoreListing() guidelines
I am open to disscusion
> feat: implement review request open store

- lib/features/home_view/widgets/science_clubs_section.dart
- lib/widgets/big_preview_card.dart
- lib/widgets/tile_splash.dart
Idk why splash doesn't work in my code. Tile splash with stack widget don't work aswell. (In first option gesture detector works properly) #456
> Feat/add tap detection on whole big preview card (and splash)

- lib/features/guide_view/guide_view.dart
- lib/l10n/app_pl.arb
Add "Share your idea" mechanism
> 425 feat add send your idea link at guide tile

- lib/features/home_view/home_view.dart
- lib/features/home_view/widgets/buildings_section/buildings_section.dart
- lib/features/home_view/widgets/paddings.dart
- removed safezone 
- added padding to last element
> fix: Remove bottom nav bar strip

- lib/features/digital_guide_view/presentation/widgets/digital_guide_nav_link.dart
> fix(digital-guide): text overflow

- lib/features/bottom_nav_bar/bottom_nav_bar.dart
- lib/features/bottom_scroll_sheet/drag_handle.dart
- lib/features/home_view/widgets/nav_actions_section.dart
- lib/features/navigator/root_view.dart
- lib/features/parking_chart/chart_elements/chart_grid.dart
- lib/features/parking_chart/chart_elements/chart_line.dart
- lib/features/parking_chart/parking_chart.dart
- lib/theme/hex_color.dart
- lib/widgets/search_box.dart
- pubspec.yaml
I reorganized pubspec.yaml. I divided this file into categories to have cleaner look for our dependencies.
> refactor: reorganize dependencies

- android/gradle/wrapper/gradle-wrapper.properties
- android/settings.gradle
- lib/features/digital_guide_view/tabs/adapted_toilets/data/repository/adapted_toilets_repository.dart
- pubspec.yaml
1. Update Gradle 7.5 to 8.9
2. Update AGP 7.x to 8.x
> Update Gradle 7.5 -> 8.9, update AGP 7.x -> 8.x

- lib/features/digital_guide_view/presentation/widgets/digital_guide_carousel.dart
- lib/features/digital_guide_view/presentation/widgets/digital_guide_photo_row.dart
- pubspec.yaml
#527 
[Simulator Screen Recording - iPhone 16 Plus - 2025-01-17 at 19.42.00.mp4.zip](https://github.com/user-attachments/files/18458572/Simulator.Screen.Recording.-.iPhone.16.Plus.-.2025-01-17.at.19.42.00.mp4.zip)
Sorry for sending video in zip but I don't have time and file is too big.
> feat(digital-guide): add gallery

- lib/features/digital_guide_view/data/models/region.dart
- lib/features/digital_guide_view/tabs/rooms/data/repository/rooms_repository.dart
- lib/features/digital_guide_view/tabs/rooms/domain/digital_guide_rooms_use_cases.dart
- lib/features/digital_guide_view/tabs/rooms/presentation/digital_guide_room_level.dart
- lib/features/digital_guide_view/tabs/rooms/presentation/digital_guide_rooms_expansion_tile_content.dart
- lib/features/home_view/widgets/nav_actions_section.dart
> feat(digital-guide): add support for levels

- lib/features/about_us_view/about_us_view.dart
- lib/features/app_changelog/app_changelog.dart
- lib/features/app_changelog/widgets/app_changelog_list.dart
- lib/features/bottom_scroll_sheet/sheet_layout_scheme.dart
- lib/features/department_detail_view/department_detail_view.dart
- lib/features/departments_view/departments_view.dart
- lib/features/digital_guide_view/presentation/digital_guide_view.dart
- lib/features/digital_guide_view/tabs/adapted_toilets/presentation/adapted_toilet_detail_view.dart
- lib/features/digital_guide_view/tabs/micronavigation/presentation/micronavigation_detail_view.dart
- lib/features/digital_guide_view/tabs/rooms/presentation/digital_guide_room_detail_view.dart
- lib/features/home_view/home_view.dart
- lib/features/home_view/widgets/logo_app_bar.dart
- lib/features/navigator/app_router.dart
- lib/features/navigator/root_view.dart
- lib/features/science_club_detail_view/science_club_detail_view.dart
- lib/features/science_club_detail_view/widgets/about_us_section_loading.dart
- lib/features/science_clubs_filters/filters_sheet.dart
- lib/features/science_clubs_view/widgets/sci_clubs_scaffold.dart
- lib/features/sks-menu/presentation/sks_menu_screen.dart
- lib/features/sks_chart/presentation/sks_chart_sheet.dart
- lib/main.dart
- lib/widgets/detail_views/detail_view_app_bar.dart
- lib/widgets/horizontal_symmetric_safe_area.dart
- lib/widgets/search_box_app_bar.dart
I think its even now but honestly I dont know anymore and i think it evens it in the whole application
> fix: even horizontal allignment

- lib/features/digital_guide_view/presentation/widgets/digital_guide_features_section.dart
- lib/features/digital_guide_view/readme.md
- lib/features/digital_guide_view/tabs/lodge/data/models/digital_guide_lodge.dart
- lib/features/digital_guide_view/tabs/lodge/data/repository/lodges_repository.dart
- lib/features/digital_guide_view/tabs/lodge/presentation/digital_guide_lodge_expansion_tile_content.dart
- lib/l10n/app_pl.arb
> Add lodge to digital guide

- lib/features/digital_guide_view/presentation/widgets/digital_guide_photo_row.dart
Now it's showing full screen image instead of carousel when there is one image.
> fix(digital-guide): infinite 1 image carousel

- lib/features/digital_guide_view/data/models/region.dart
- lib/features/digital_guide_view/presentation/widgets/digital_guide_features_section.dart
- lib/features/digital_guide_view/readme.md
- lib/features/digital_guide_view/tabs/lifts/data/models/digital_guide_lift.dart
- lib/features/digital_guide_view/tabs/lifts/data/repository/lifts_repository.dart
- lib/features/digital_guide_view/tabs/lifts/domain/digital_guide_lifts_use_cases.dart
- lib/features/digital_guide_view/tabs/lifts/presentation/digital_guide_lift_detail_view.dart
- lib/features/digital_guide_view/tabs/lifts/presentation/digital_guide_lift_level.dart
- lib/features/digital_guide_view/tabs/lifts/presentation/digital_guide_lifts_expansion_tile_content.dart
- lib/features/navigator/app_router.dart
- lib/features/navigator/utils/navigation_commands.dart
- lib/l10n/app_pl.arb
> Add lifts to digital guide

- .fvm/flutter_sdk
- .fvm/fvm_config.json
- .fvmrc
- lib/features/buildings_view/building_tile.dart
- lib/features/digital_guide_view/presentation/digital_guide_view.dart
- lib/features/digital_guide_view/presentation/widgets/digital_guide_loading_view.dart
created loading screen for digital guide view
> /feat(digital-guide): create loading screen #483

- lib/features/sks/sks_chart/presentation/sks_chart_sheet.dart
> feat(sks-chart): shimmer loading (#587)

- lib/features/sks/sks_menu/data/models/sks_menu_response.dart
- lib/features/sks/sks_menu/data/models/sks_opening_hours.dart
- lib/features/sks/sks_menu/data/repository/sks_menu_repository.dart
- lib/features/sks/sks_menu/presentation/sks_menu_screen.dart
- lib/features/sks/sks_menu/presentation/widgets/sks_menu_header.dart
- lib/l10n/app_pl.arb
I added opening hours in header section to sks menu, I think it looks quite clean this way:
> feat(sks-menu): add opening hours 

- lib/features/digital_guide/tabs/structure/data/bussiness/toilets_accessibility_comments_manager.dart
- lib/features/digital_guide/tabs/structure/data/models/toilet.dart
- lib/features/digital_guide/tabs/structure/presentation/views/region_view.dart
- lib/features/digital_guide/tabs/structure/presentation/views/toilets_view.dart
- lib/features/navigator/app_router.dart
- lib/features/navigator/utils/navigation_commands.dart
- lib/l10n/app_pl.arb
> Toilets in structure tab

- lib/widgets/my_alert_dialog.dart
same as #739 but for dialog's buttons size font in the my alert
> fix: my alert dialog font size buttons on normal size font
