lib/config/map_view_config.dart
lib/features/buildings_map/controllers.dart
lib/features/buildings_map/utils.dart
lib/shared_repositories/buildings_repository/building_model.dart
lib/shared_repositories/buildings_repository/getMapBuildings.graphql

#97 
I added the filters mentioned and improve graphql&model of bulidings

feature: add new filter to bulding search

---

lib/config/map_view_config.dart
lib/config/transitions.dart
lib/features/home_view/widgets/news_section.dart
lib/features/map_view/utils/map_marker_utils.dart
lib/features/navigator/app_router.dart
lib/widgets/loading_widgets/specific_imitations/big_preview_card_loading.dart

Don't be scared with stacked PRs :) this one is very simple. Just make reviews of every one of them and I'll merge them in the end together.
- Actually it is observable on android too, but android has a bit different scroll mechanics, so in ios it was more obvious
- very simple fix, just as I anticipated, one section had different hight while loading than in loaded state and with `ListView.builder` it was rebuilding just in that specific moment and trigger the rebuild and weird scroll mechanics.
- Fixed with simple calculations and sized box.
https://github.com/user-attachments/assets/3f5303c6-4758-4e30-8a1f-e07f44191e46
https://github.com/user-attachments/assets/3056ea0c-c801-4b1a-aba4-d172eed9c8f5
this was main problem.  
Alternative solution is to preserve `newsRepository` provider in …

Fix/ eliminate jumping scroll in home view

---

lib/features/parkings_view/widgets/parking_wide_tile_card.dart
lib/l10n/app_pl.arb

At first glance, I thought about setting the street address in the data layer, but then I thought about localization and finally ended up setting the "ul. "  or "st. " prefix in the ui layer.

#124 - parking typos - fix

---

lib/widgets/wide_tile_card.dart

Splash now works correctly on fields of study tile and on building tile (used in map view)
[splash_departments.webm](https://github.com/user-attachments/assets/3053db8e-b14f-4e1f-a3d0-0a71fb0ff976)
[splash_buildings.webm](https://github.com/user-attachments/assets/11641950-4da5-44cd-9fd3-d39db9beda85)

#164 - add splash on field of study tile

---

lib/api_base/ttl/local_timestamp_repository.dart
lib/config/shared_prefs.dart
lib/features/parkings_view/repository/local_fav_parking_repository.dart
lib/features/parkings_view/widgets/parking_favourite.dart
lib/features/parkings_view/widgets/parking_wide_tile_card.dart
pubspec.yaml

I used shared_preferences and I updated version to 2.3.2

feat/ add favorite parkings feature

---

lib/features/academic_calendar/utils/counter_digits.dart
lib/features/academic_calendar/utils/localize_academic_day.dart
lib/features/academic_calendar/utils/localize_counter_message.dart
lib/features/academic_calendar/widgets/countdown_widget/exam_session_countdown.dart
lib/l10n/app_pl.arb

- During the holiday season, the counter counts down the days until the start of the next semester.
- During the exam session, the counter tracks the days remaining until the session ends.
- After the semester starts and before the session begins, the counter displays the days between these two events.
- It's crucial to regularly update the dates in the API.

Feat/ add days to semester mode

---

lib/features/parking_chart/widgets/chart_widget.dart
lib/features/parkings_view/models/parking.dart
lib/features/parkings_view/widgets/parking_wide_tile_card.dart

- It would be perfect to notify the person reporting the error for morale support.  
- I’ve also implemented a mechanism that ensures that the number of available spaces is always equal to or greater than 0 (never negative, as happened on 24/09/2024).

#230 - replace decimal numbers with integers at parking's page & make sure that free slots are always >= 0

---

lib/config/map_view_config.dart
lib/features/map_view/widgets/map_widget.dart
pubspec.yaml

I've added cachce support for map tiles. 
- I've been wondering if flushing map's cache should be possible from an API. I've decided not to implement that feature for now (maps don't change that often I guess,at least ones that we use).  If you think differently, I can change it of course
- in the Hive implementation you can see `null` passed in place of directory path. Documentation says that if we use Hive already in the project, there's no need to provide it again. I guess that's correct in our situation. 
- do you know any ways to change if caching actually works (some logging or sth)?

#221 - add cache support for map tiles

---

lib/config/ui_config.dart
lib/features/department_detail_view/widgets/science_clubs_section.dart
lib/features/home_view/widgets/science_clubs_section.dart
lib/features/science_clubs_view/widgets/science_club_card.dart
lib/widgets/big_preview_card.dart
lib/widgets/dual_text_max_lines.dart

#263 
- Checkmarks are now displayed in every place that study circle tile's present.
- I've refactored logic responsible for determining if checkmarks should be displayed.
- Please check the visual effect and tell if you like it ;)
- I wonder if we should implement some kind of checkmark even in the study circle's details?

Feat/ add verified checkmark to science clubs in all other places

---

lib/config/shared_prefs.dart
lib/features/app_streak/business/get_days_use_case.dart
lib/features/app_streak/data/last_entry_repo.dart
lib/features/app_streak/data/streak_start_repo.dart
lib/features/app_streak/data/timstamp_repo_mixin.dart
lib/features/app_streak/presentation/app_streak_counter.dart
lib/features/home_view/home_view.dart
lib/features/home_view/keep_alive_home_view_providers.dart
lib/l10n/app_pl.arb
lib/utils/timestamp.dart

Feat/ add app's streak counter

---

lib/config/ui_config.dart
lib/features/guide_detail_view/guide_detail_view.dart
lib/features/guide_detail_view/repository/getGuideDetails.graphql
lib/features/guide_detail_view/utils/get_the_latest_date.dart
lib/l10n/app_pl.arb

Okay, I added dates
- last updated 
- created
to every guide on detail's page. I think extracting the newest date on modified and created from all questions faq's. If you think there is the better option such us dates under each faq let me know!
ss's:

feature: add dates to guide

---

lib/features/about_us_view/utils/html_util_extensions.dart

1. Justify removed on html widget
2. If sci club hasn't set up it to justify by default is aligned to left
3. Guide text align is to left
ss's:

feature: change text-align justify to left

---

lib/features/about_us_view/utils/html_util_extensions.dart

changed underline color to black mirage by default on element which contains underline but are not links 
some ss's:

feat: change pomegrenade underline on not link do black

---

lib/config/url_config.dart
lib/features/navigator/navigation_controller.dart
lib/features/navigator/utils/navigation_commands.dart
lib/utils/launch_url_util.dart

so previously if there was a deeplink in some text or guide or smth we just opened it like any other and relied on the os system to open good tab in our app.
And it even kinda worked. But had some drawbacks:
1. IOS didn't work (xd) - generally in this scenario ios never works (at least that's what i read) so this change is needed here. If we open a link ios assume we can't handle it internally, which is not the case here. we need to handle it ourselves. Disclaimer: i don't think ios deeplinks work at all for our app, but this change removes the worst case where someone can notice it.
2. on android it worked but had one drawback: back button didn't move us back to the place where we opened it. Which imo is kinda bad UX. Now you can always make a nice return to the previous screen.

feat: handle in app deep links

---

analysis_options.yaml
lib/features/bottom_scroll_sheet/data_list.dart
lib/features/bottom_scroll_sheet/map_view_pop_behaviour.dart
lib/features/buildings_view/building_tile.dart
lib/features/buildings_view/buildings_view.dart
lib/features/buildings_view/controllers.dart
lib/features/map_view/controllers/controllers_set.dart
lib/features/map_view/controllers/map_controller.dart
lib/features/map_view/widgets/load_animated_controller.dart
lib/features/map_view/widgets/map_widget.dart
lib/features/parkings_view/controllers.dart
lib/features/parkings_view/parkings_view.dart
lib/features/parkings_view/widgets/parking_tile.dart
pubspec.yaml

https://github.com/user-attachments/assets/45dfee6d-006c-417a-81fa-c1e7abcf65c0

Feat/ animate maps camera

---

lib/features/parking_chart/chart_elements/labels_left.dart

#243 
- I couldn't reproduce the bug. Tested on various devices (different width and height of the screen), everything worked fine.  
- I've decided to increase `reservedSize` value from 30 to 32. I think that will resolve imo rare issue.

Fix: fix chart labels

---

lib/features/home_view/home_view.dart

By default AppBar adds padding if there is notch or any system padding.
To fix we can add the same padding to others elements and align them in column with logo.

Add padding to all elements if there is system padding

---

lib/config/nav_bar_config.dart
lib/features/about_us_view/about_us_view.dart
lib/features/department_detail_view/department_detail_view.dart
lib/features/departments_view/departments_view.dart
lib/features/guide_detail_view/guide_detail_view.dart
lib/features/navigation_tab_view/navigation_tab_view.dart
lib/features/navigator/navigation_controller.dart
lib/features/navigator/utils/navigation_commands.dart
lib/features/science_club_detail_view/science_club_detail_view.dart
lib/features/science_clubs_view/widgets/sci_clubs_scaffold.dart
lib/features/sks-menu/presentation/sks_menu_screen.dart
lib/widgets/detail_views/detail_view_app_bar.dart
lib/widgets/detail_views/pop_button.dart
lib/widgets/search_box_app_bar.dart

This has started as simple button's text fix, but ended up with a nice reusable feature.
Now the `DetailViewPopButton` that exists in some of our app bars extracts the label from the navigation stack, so no hardcoding is needed for it to have a proper button title.
This is made by @thesun901, with my noticable involvement, so you guys gotta make us a review @mikolaj-jalocha @tomasz-trela 
@thesun901 can make a review too to see and review my latest changes. 
tell us what you think :P

feat: add navigation aware back button

---

lib/config/ui_config.dart
lib/features/navigation_tab_view/widgets/notification_button.dart
lib/features/sks-menu/presentation/sks_menu_screen.dart

refactor: fix padding

---

lib/features/map_view/controllers/map_controller.dart

map_controller.dart: prevent _controllerCompleter from completing AnimatedMapController again after rotating
^ pretty self explainatory - error occured because app tried to complete already completed controller.

fix: eliminate rotate map error

---

lib/api_base_rest/cache/cache.dart
lib/api_base_rest/cache/cache_manager.dart
lib/api_base_rest/client/offline_error.dart
lib/features/sks-menu/data/models/sks_menu_response.dart
lib/features/sks-menu/data/repository/sks_menu_repository.dart
lib/features/sks-menu/presentation/sks_menu_screen.dart
lib/features/sks-menu/presentation/widgets/sks_menu_section.dart
lib/features/sks-menu/presentation/widgets/technical_message.dart
lib/l10n/app_pl.arb
lib/widgets/my_error_widget.dart

1. Adjusted error handling
- previously we had shown sks animation with any error
- now we show:
- sks animation when the menu is not available (that's not really an exception, just a normal situation)
- offline animation when we don't have internet connection
- our `MyErrorWidget` on any other error
2. Added caching
- we cache the data for 1 day, only when the available menu is up to date
- we always invalidate the cache when the cached data is from the previous day (after midnight)
3. pull to refresh
- we invalidate the cache and redo the request

Feat/ Adjust SKS error handling && add REST API caching

---

lib/config/ui_config.dart
lib/features/digital_guide_view/presentation/digital_guide_view.dart
lib/features/digital_guide_view/presentation/widgets/accessibility_information_card.dart
lib/features/digital_guide_view/presentation/widgets/report_change_button.dart
lib/features/digital_guide_view/tabs/amenities/presentation/amenities_expansion_tile_content.dart
lib/features/digital_guide_view/tabs/surrounding/presentation/surroundings_expansion_tile_content.dart
lib/widgets/detail_views/contact_section.dart

- Small paddings changes in amnesties expansion tile
- Improving visual aspect of Surroundings expension tile
- Small changes to other parts of digital guide UI

fix(digital-guide): ui changes to amnesties and surroundings tiles

---

lib/features/digital_guide_view/presentation/digital_guide_view.dart
lib/features/digital_guide_view/tabs/adapted_toilets/data/models/adapted_toilet.dart
lib/features/digital_guide_view/tabs/adapted_toilets/presentation/adapted_toilet_detail_view.dart
lib/features/home_view/widgets/nav_actions_section.dart

I tried to use DigitalGuidePhotoRow in adapted toilets and I even fixed row stretching in this widget but it looked awkward because of the images ratio.

Round images in adapted toilets

---

lib/config/ui_config.dart
lib/features/digital_guide_view/presentation/widgets/accessibility_button.dart
lib/features/digital_guide_view/tabs/accessibility_dialog/business/accessibility_mode_service.dart
lib/features/digital_guide_view/tabs/accessibility_dialog/business/top_level_modes.dart
lib/features/digital_guide_view/tabs/accessibility_dialog/data/accessibility_mode_repository.dart
lib/features/digital_guide_view/tabs/accessibility_dialog/data/modes.dart
lib/features/digital_guide_view/tabs/accessibility_dialog/presentation/accessibility_dialog.dart
lib/features/digital_guide_view/tabs/accessibility_dialog/presentation/checkboxes_list.dart
lib/features/digital_guide_view/tabs/accessibility_dialog/presentation/labels.dart
lib/features/digital_guide_view/tabs/accessibility_dialog/presentation/mode_checkbox.dart
lib/features/digital_guide_view/tabs/accessibility_dialog/presentation/red_dialog.dart
lib/l10n/app_pl.arb

so when it comes to code, i went kinda crazy...
cause this could have been easily hardcoded, and I'm not sure if the layers of abstractions are not too much a bit for the use case. Also some functional programming concepts were used, allowing us to define any number of custom accessibility modes and nest them into each other in any way we want. So please tell me if this is still readable or would you prefer something more hardcoded in a way, and not fully abstract.
this could be usefull to read before the review: https://dart.dev/language/class-modifiers#sealed

feat(digital-guide): add accessibility modes dialog

---

lib/features/digital_guide_view/presentation/widgets/digital_guide_features_section.dart
lib/features/digital_guide_view/readme.md
lib/features/digital_guide_view/tabs/dressing_room/data/models/digital_guide_dressing_room.dart
lib/features/digital_guide_view/tabs/dressing_room/data/repository/dressing_rooms_repository.dart
lib/features/digital_guide_view/tabs/dressing_room/presentation/digital_guide_dressing_rooms_expansion_tile.dart
lib/features/digital_guide_view/tabs/lodge/presentation/digital_guide_lodge_expansion_tile_content.dart
lib/l10n/app_pl.arb

#541 
- 1:1 changes as with lodges (I also changed working hours to be displayed only when information's available)
- I was thinking for a moment whether to create single UI that'd handle lodges and dressing rooms but finally decided just to copy and adjust existing solution. Imo digital guide structure is complicated, there's no point in complicating it even more, minor code repetition is not a sin in this scenario I believe 😆 But let me know WDYT

Add dressing rooms to digital guide

---

lib/api_base/schema.graphql
lib/config/ttl_config.dart
lib/features/academic_calendar/widgets/academic_calendar_consumer.dart
lib/features/home_view/home_view.dart
lib/features/offline_messages/messages_config.dart
lib/features/planner_advert/repository/getPlannerAdvertContent.graphql
lib/features/planner_advert/repository/planner_advert_repository.dart
lib/features/planner_advert/widgets/planner_advert_widget.dart
lib/features/sks-menu/presentation/sks_menu_screen.dart
lib/l10n/app_pl.arb
lib/widgets/loading_widgets/simple_previews/horizontal_rectangular_section_loading.dart
lib/widgets/technical_message.dart

- whole section is clickable
- when disabled, nothing is shown 
- I didn't implement adverts in other places (I don't know exactly where and wanted to sort out the most important for now) but if you guys think it belongs to the scope of this task I will do that.
- I reused `technicalMessage` widget. Whole operation wasn't intrusive and easy to perform. I decided not to implement separate widget for that, new improvements seems useful afterall.

Add planner advert

---

lib/features/sks_menu/presentation/sks_menu_screen.dart

Fixed that unclickable button issue. The problem was that"Pokaż ostatnio dostępne menu" button was under the image, but i managed to make it clickable and I just moved the whole section up. This is the outcome:
And without the button, if the latest menu is not available:

bug: Sks menu button fix
